# {Project Title}📝

![Banner](./assets/banner.jpeg)

## Topic
*What problem are you (or your stakeholder) trying to address?*
📝 <!-- Answer Below -->

## Project Question
*What specific question are you seeking to answer with this project?*
*This is not the same as the questions you ask to limit the scope of the project.*
📝 <!-- Answer Below -->

## What would an answer look like?
*What is your hypothesized answer to your question?*
📝 <!-- Answer Below -->

## Data Sources
*What 3 data sources have you identified for this project?*
*How are you going to relate these datasets?*
📝 <!-- Answer Below -->

## Approach and Analysis
*What is your approach to answering your project question?*
*How will you use the identified data to answer your project question?*
📝 <!-- Start Discussing the project here; you can add as many code cells as you need -->

In [5]:
from io import BytesIO
from pathlib import Path
from zipfile import ZipFile
from getpass import getpass

import pandas as pd
import requests

data_folder = Path("data")
data_folder.mkdir(exist_ok=True)

print("Setup complete")

Setup complete

In [10]:
movielens_url = (
    "https://files.grouplens.org/datasets/"
    "movielens/ml-latest-small.zip"
)

response = requests.get(movielens_url, timeout=60)
response.raise_for_status()

with ZipFile(BytesIO(response.content)) as zip_file:
    zip_file.extractall(data_folder)

movielens_folder = data_folder / "ml-latest-small"

movies = pd.read_csv(movielens_folder / "movies.csv")
ratings = pd.read_csv(movielens_folder / "ratings.csv")
links = pd.read_csv(movielens_folder / "links.csv")

print("Movies:", movies.shape)
print("Ratings:", ratings.shape)
print("Links:", links.shape)

movies.head()

Movies: (9742, 3)
Ratings: (100836, 4)
Links: (9742, 3)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [12]:
links["tconst"] = (
    "tt"
    + links["imdbId"].astype("Int64").astype(str).str.zfill(7)
)

movielens_data = movies.merge(
    links,
    on="movieId",
    how="left"
)

movielens_data.head()

,movieId,title,genres,imdbId,tmdbId,tconst
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,tt0114709
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0,tt0113497
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,15602.0,tt0113228
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,31357.0,tt0114885
4,5,Father of the Bride Part II (1995),Comedy,113041,11862.0,tt0113041

In [14]:
imdb_url = "https://datasets.imdbws.com/title.ratings.tsv.gz"

imdb_ratings = pd.read_csv(
    imdb_url,
    sep="\t",
    compression="gzip",
    na_values="\\N"
)

print("IMDb ratings:", imdb_ratings.shape)
imdb_ratings.head()

IMDb ratings: (1714571, 3)

      tconst  averageRating  numVotes
0  tt0000001            5.7      2231
1  tt0000002            5.4       326
2  tt0000003            6.4      2385
3  tt0000004            5.0       202
4  tt0000005            6.2      3097

In [16]:
movie_data = movielens_data.merge(
    imdb_ratings,
    on="tconst",
    how="left"
)

print("Combined MovieLens and IMDb:", movie_data.shape)
movie_data.head()

Combined MovieLens and IMDb: (9742, 8)

,movieId,title,genres,imdbId,tmdbId,tconst,averageRating,numVotes
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,tt0114709,8.3,1200526.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0,tt0113497,7.1,419988.0
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,15602.0,tt0113228,6.7,31990.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,31357.0,tt0114885,6.1,14207.0
4,5,Father of the Bride Part II (1995),Comedy,113041,11862.0,tt0113041,6.1,45979.0

In [18]:
project_movies = (
    movie_data
    .dropna(subset=["tmdbId", "averageRating", "numVotes"])
    .query("numVotes >= 25000")
    .sort_values(
        ["averageRating", "numVotes"],
        ascending=False
    )
    .head(25)
    .copy()
)

project_movies["tmdbId"] = project_movies["tmdbId"].astype(int)

print("Selected movies:", project_movies.shape)
project_movies.head()

Selected movies: (25, 8)

,movieId,title,genres,imdbId,tmdbId,tconst,averageRating,numVotes
9497,170705,Band of Brothers (2001),Action|Drama|War,185906,331214,tt0185906,9.4,606350.0
9318,159817,Planet Earth (2006),Documentary,795176,192040,tt0795176,9.4,236948.0
9511,171011,Planet Earth II (2016),Documentary,5491994,420714,tt5491994,9.4,177044.0
277,318,"Shawshank Redemption, The (1994)",Crime|Drama,111161,278,tt0111161,9.3,3243182.0
9634,179135,Blue Planet II (2017),Documentary,6769208,463612,tt6769208,9.3,58749.0

In [21]:
tmdb_token = getpass("Paste your TMDB API Read Access Token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5NDNlNmRjNmI0YmZjYmIwM2RiMTM5NDAwYzA1YzY4NSIsIm5iZiI6MTc5MDU2Mjk3MS43NTAwMDAyLCJzdWIiOiI2YWI5ZDI5YjFhNWY2OTgxYWExYjcwMGYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.-emWTtmlZeRpVcNgSzTEj8zz58QFIVxN_Per_u4ALvc")

tmdb_headers = {
    "Authorization": f"Bearer {tmdb_token}",
    "accept": "application/json"
}

print("TMDB token received")

TMDB token received

In [23]:
test_movie_id = int(project_movies.iloc[0]["tmdbId"])

test_url = (
    f"https://api.themoviedb.org/3/movie/"
    f"{test_movie_id}/watch/providers"
)

test_response = requests.get(
    test_url,
    headers=tmdb_headers,
    timeout=30
)

print("Status code:", test_response.status_code)

Status code: 404

In [26]:
provider_records = []
missing_movies = []

for tmdb_id in project_movies["tmdbId"]:
    url = (
        f"https://api.themoviedb.org/3/movie/"
        f"{tmdb_id}/watch/providers"
    )

    response = requests.get(
        url,
        headers=tmdb_headers,
        timeout=30
    )

    # Skip movie IDs that TMDB cannot find
    if response.status_code == 404:
        missing_movies.append(tmdb_id)
        continue

    response.raise_for_status()

    us_results = response.json().get("results", {}).get("US", {})

    for access_type in ["flatrate", "free", "ads", "rent", "buy"]:
        providers = us_results.get(access_type, [])

        for provider in providers:
            provider_records.append({
                "tmdbId": tmdb_id,
                "provider_id": provider["provider_id"],
                "provider_name": provider["provider_name"],
                "access_type": access_type,
                "country": "US"
            })

watch_providers = pd.DataFrame(
    provider_records,
    columns=[
        "tmdbId",
        "provider_id",
        "provider_name",
        "access_type",
        "country"
    ]
)

print("TMDB provider records:", watch_providers.shape)
print("Missing TMDB movie IDs:", missing_movies)

watch_providers.head()

TMDB provider records: (213, 5)
Missing TMDB movie IDs: [331214, 192040, 420714, 463612, 409926, 374430, 200813, 134481, 69372, 26397, 419787, 500609]

   tmdbId  provider_id                  provider_name access_type country
0     278          257                         fuboTV    flatrate      US
1     278          583            MGM+ Amazon Channel    flatrate      US
2     278         2383                          Philo    flatrate      US
3     278          636  MGM Plus Roku Premium Channel    flatrate      US
4     278           10                   Amazon Video        rent      US

In [29]:
subscription_providers = watch_providers[
    watch_providers["access_type"] == "flatrate"
].copy()

analysis_data = project_movies.merge(
    subscription_providers,
    on="tmdbId",
    how="left"
)

print("Final combined dataset:", analysis_data.shape)
analysis_data.head()

Final combined dataset: (68, 12)

,movieId,title,genres,imdbId,tmdbId,tconst,averageRating,numVotes,provider_id,provider_name,access_type,country
0,170705,Band of Brothers (2001),Action|Drama|War,185906,331214,tt0185906,9.4,606350.0,NaN,NaN,NaN,NaN
1,159817,Planet Earth (2006),Documentary,795176,192040,tt0795176,9.4,236948.0,NaN,NaN,NaN,NaN
2,171011,Planet Earth II (2016),Documentary,5491994,420714,tt5491994,9.4,177044.0,NaN,NaN,NaN,NaN
3,318,"Shawshank Redemption, The (1994)",Crime|Drama,111161,278,tt0111161,9.3,3243182.0,257.0,fuboTV,flatrate,US
4,318,"Shawshank Redemption, The (1994)",Crime|Drama,111161,278,tt0111161,9.3,3243182.0,583.0,MGM+ Amazon Channel,flatrate,US

In [31]:
project_movies.to_csv(
    data_folder / "project_movies.csv",
    index=False
)

watch_providers.to_csv(
    data_folder / "watch_providers.csv",
    index=False
)

analysis_data.to_csv(
    data_folder / "streamhaven_analysis_data.csv",
    index=False
)

print("Files saved successfully in the data folder")

Files saved successfully in the data folder

In [33]:
print("MovieLens movie records:", len(movies))
print("IMDb rating records:", len(imdb_ratings))
print("TMDB provider records:", len(watch_providers))
print("Final combined records:", len(analysis_data))

MovieLens movie records: 9742
IMDb rating records: 1714571
TMDB provider records: 213
Final combined records: 68

## Resources and References
*What resources and references have you used for this project?*
📝 <!-- Answer Below -->

In [34]:
# ⚠️ Make sure you run this cell at the end of your notebook before every submission!
!jupyter nbconvert --to python source.ipynb

[NbConvertApp] Converting notebook source.ipynb to python
[NbConvertApp] Writing 1261 bytes to source.py